FROM node:20-alpine

WORKDIR /app

RUN chown node:node /app

COPY --chown=node:node package.json yarn.lock ./

USER node

RUN yarn install

COPY --chown=node:node . .

EXPOSE 3000

CMD ["yarn", "start"]
