import { OcorrenciaModel } from "./model";

export const ocorrencias: OcorrenciaModel[] = [
    {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Investigado',
        status: 'Aguardando parecer',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
    },
    {
        denuncia: '123ABC',
        data: '2022-02-20',
        condicao: 'Condição 2',
        gravidade: 'Em investigação',
        status: 'Aguardando Finalização',
        andamentoCaso: 'Andamento do Caso 2',
        acao: 'Ação 2',
        causa: 'Causa 2',
        cidade: 'Cidade 2',
        regiao: 'Região 2',
    },
    {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Em investigação',
        status: 'Status 1',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
      },
      {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Investigado',
        status: 'Aguardando parecer',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
    },
    {
        denuncia: '123ABC',
        data: '2022-02-20',
        condicao: 'Condição 2',
        gravidade: 'Em investigação',
        status: 'Aguardando Finalização',
        andamentoCaso: 'Andamento do Caso 2',
        acao: 'Ação 2',
        causa: 'Causa 2',
        cidade: 'Cidade 2',
        regiao: 'Região 2',
    },
    {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Em investigação',
        status: 'Status 1',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
      },
      {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Investigado',
        status: 'Aguardando parecer',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
    },
    {
        denuncia: '123ABC',
        data: '2022-02-20',
        condicao: 'Condição 2',
        gravidade: 'Em investigação',
        status: 'Aguardando Finalização',
        andamentoCaso: 'Andamento do Caso 2',
        acao: 'Ação 2',
        causa: 'Causa 2',
        cidade: 'Cidade 2',
        regiao: 'Região 2',
    },
    {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Em investigação',
        status: 'Status 1',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
      },
      {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Investigado',
        status: 'Aguardando parecer',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
    },
    {
        denuncia: '123ABC',
        data: '2022-02-20',
        condicao: 'Condição 2',
        gravidade: 'Em investigação',
        status: 'Aguardando Finalização',
        andamentoCaso: 'Andamento do Caso 2',
        acao: 'Ação 2',
        causa: 'Causa 2',
        cidade: 'Cidade 2',
        regiao: 'Região 2',
    },
    {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Em investigação',
        status: 'Status 1',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
      },
      {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Investigado',
        status: 'Aguardando parecer',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
    },
    {
        denuncia: '123ABC',
        data: '2022-02-20',
        condicao: 'Condição 2',
        gravidade: 'Em investigação',
        status: 'Aguardando Finalização',
        andamentoCaso: 'Andamento do Caso 2',
        acao: 'Ação 2',
        causa: 'Causa 2',
        cidade: 'Cidade 2',
        regiao: 'Região 2',
    },
    {
        denuncia: '123XYZ',
        data: '2022-02-19',
        condicao: 'Condição 1',
        gravidade: 'Em investigação',
        status: 'Status 1',
        andamentoCaso: 'Andamento do Caso 1',
        acao: 'Ação 1',
        causa: 'Causa 1',
        cidade: 'Cidade 1',
        regiao: 'Região 1',
      },
      {
        denuncia: '123ABC',
        data: '2022-02-20',
        condicao: 'Condição 2',
        gravidade: 'Investigado',
        status: 'Status 2',
        andamentoCaso: 'Andamento do Caso 2',
        acao: 'Ação 2',
        causa: 'Causa 2',
        cidade: 'Cidade 2',
        regiao: 'Região 2',
      }
  ];