name: Build e Deploy Frontend - teste

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Definir nome da imagem
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER=$OWNER" >> $GITHUB_ENV

      - name: Build da imagem do frontend
        run: |
          docker build -t ghcr.io/$OWNER/zerobito-frontend:latest .

      - name: Push para GHCR
        run: |
          docker push ghcr.io/$OWNER/zerobito-frontend:latest

      - name: Deploy na VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /opt/apps/frontend
            sudo docker compose pull image: ghcr.io/$OWNER/zerobito-frontend:latest
            sudo docker compose up -d
            sudo docker image prune -f